language: python
python:
    - "2.7"
# command to install dependencies
install:
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install tools/cli
# command to run tests
script:
    - pep8 tools/cli
    - py.test tools/cli -v
